# pvc.yaml
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: raw-data-new-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  volumeName: raw-data-pv