# pv.yaml
apiVersion: v1
kind: PersistentVolume
metadata:
  name: shared-pv
  labels:
    type: shared-storage
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /mnt/data
