# service.yaml
apiVersion: v1
kind: Service
metadata:
  name: preprocess-service
spec:
  type: LoadBalancer
  selector:
    app: preprocess
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5000
