# preprocess_deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: preprocess-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: preprocess
  revisionHistoryLimit: 2
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1
  template:
    metadata:
      labels:
        app: preprocess
    spec:
      containers:
      - name: preprocess-container
        image: adamrusai/preprocess:latest
        volumeMounts:
        - name: data-vol
          mountPath: "/mnt"
      volumes:
      - name: data-vol
        persistentVolumeClaim:
          claimName: data-pvc
      restartPolicy: Always