# preprocess_deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: preprocess-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: preprocess
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1
  template:
    metadata:
      labels:
        app: preprocess
    spec:
      containers:
      - name: preprocess-container
        image: adamrusai/preprocess:latest # Ensure this matches your Docker Hub image
        ports:
        - containerPort: 5000
        volumeMounts:
        - name: shared-storage
          mountPath: "/data"
      volumes:
      - name: shared-storage
        persistentVolumeClaim:
          claimName: shared-pvc
      restartPolicy: Always