# train_deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: train-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: train
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1
  template:
    metadata:
      labels:
        app: train
    spec:
      containers:
      - name: train-container
        image: adamrusai/train:latest
        volumeMounts:
        - name: data-vol
          mountPath: "/mnt"
      volumes:
      - name: data-vol
        persistentVolumeClaim:
          claimName: data-pvc 