# deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: website-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: website
  revisionHistoryLimit: 2
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1
  template:
    metadata:
      labels:
        app: website
    spec:
      containers:
      - name: website-container
        image: adamrusai/website:latest
        ports:
        - containerPort: 80
        volumeMounts:
        - name: data-vol
          mountPath: "/mnt"
      volumes:
      - name: data-vol
        persistentVolumeClaim:
          claimName: data-pvc
      restartPolicy: Always
