# deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: website-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: website
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1
  template:
    metadata:
      labels:
        app: website
    spec:
      containers:
      - name: website-container
        image: adamrusai/website:latest # Ensure this matches your Docker Hub image
        ports:
        - containerPort: 5000
        volumeMounts:
        - name: train-storage
          mountPath: /app_data
      volumes:
      - name: train-storage
        persistentVolumeClaim:
          claimName: train-pvc
      restartPolicy: Always