# website service.yaml
apiVersion: v1
kind: Service
metadata:
  name: website-service
spec:
  selector:
    app: website
  ports:
    - protocol: TCP
      port: 80  # Port exposed externally
      targetPort: 5000  # Port Flask app is running on
  type: LoadBalancer  # Type of service (use NodePort if no LoadBalancer available)