# model deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: train-deployment
spec:
  replicas: 3  # Number of replicas (adjust as needed)
  selector:
    matchLabels:
      app: train
  template:
    metadata:
      labels:
        app: train
    spec:
      containers:
      - name: train-container
        image: fourglasses  # Replace with your Docker image
        ports:
        - containerPort: 5000  # Port your Flask app is running on
        env:
        - name: SAVE_DIR
          value: /app_data  # Adjust as needed for your app
        volumeMounts:
        - name: model-storage
          mountPath: /app_data
      volumes:
      - name: train-storage
        persistentVolumeClaim:
          claimName: train-pvc  
