# deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: inference-deploy
spec:
  replicas: 5
  selector:
    matchLabels:
      app: inference
  revisionHistoryLimit: 2
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1
  template:
    metadata:
      labels:
        app: inference
    spec:
      containers:
      - name: inference-pod
        image: adamrusai/model-inference:latest # Ensure this matches your Docker Hub image
        ports:
        - containerPort: 5000
        env:
        - name: SAVE_DIR
          value: /app_data  # Adjust as needed for your app
        volumeMounts:
        - name: model-storage
          mountPath: /app_data
      volumes:
      - name: train-storage
        persistentVolumeClaim:
          claimName: train-pvc
      restartPolicy: Always